name: ML Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          pip install -r requirements.txt

      - name: Check dataset changes and retrain if needed
        run: |
          source myenv/bin/activate
          python train.py

      - name: Deploy Model to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" | tr -d '\r' > Flaskapp.pem
          chmod 600 Flaskapp.pem
          
          # Check if folder exists, if not, create it
          ssh -i Flaskapp.pem $EC2_USER@$EC2_HOST '[ -d "/home/$EC2_USER/models" ] || mkdir -p /home/$EC2_USER/models'

          # Copy model file to EC2
          scp -i Flaskapp.pem models/model_*.pkl $EC2_USER@$EC2_HOST:/home/$EC2_USER/models/

          # Restart application
          ssh -i Flaskapp.pem $EC2_USER@$EC2_HOST "sudo systemctl restart my_flask_app"
  